# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0031_auto_20190614_1203'),
        ('parlamentares', '0031_cargobloco_cargoblocopartido'),
    ]

    operations = [
    ]
